server:
  port: 3000
  basePath: ""
application:
  domain: sploitec.inc
  name: "Sploitec Buggy App"
  logo: JuiceShop_Logo.png
  favicon: favicon_js.ico
  theme: blue-lightblue # Options: bluegrey-lightgreen blue-lightblue deeppurple-amber indigo-pink pink-bluegrey purple-green deeporange-indigo
  showVersionNumber: false
  showGitHubLinks: false
  localBackupEnabled: true
  numberOfRandomFakeUsers: 2
  altcoinName: TeCoin
  privacyContactEmail: security@sploitec.inc
  customMetricsPrefix: sploitec
  chatBot:
    name: "Sploitey"
    greeting: "What's up <customer-name>, My name is <bot-name>"
    trainingData: "botDefaultTrainingData.json"
    defaultResponse: "I do not understand a word of what you've said!"
    avatar: "JuicyChatBot.png"
  recyclePage:
    topProductImage: fruit_press.jpg
    bottomProductImage: apple_pressings.jpg
  welcomeBanner:
    showOnFirstStart: true
    title: "Welcome To Our ExSPLOITable Website!"
    message: "<p>The <strong>Sploitec Buggy App</strong> is supposed to be the opposite of a secure application: It is an awareness, training, demonstration and exercise tool for security risks in modern web applications.</p>"
  cookieConsent:
    backgroundColor: "#546e7a"
    textColor: "#ffffff"
    buttonColor: "#558b2f"
    buttonTextColor: "#ffffff"
    message: "This website uses robo cookies to ensure you get the best tracking experience."
    dismissText: "Robot wants it!"
    linkText: "But robot will wait!"
    linkUrl: "INSERT_YOUR_GITHUB_LINK"
  securityTxt:
    contact: "mailto:donotreply@sploitec.inc"
    encryption: ~
    acknowledgements: "/#/score-board"
    hiring: "/#/jobs"
  easterEggPlanet:
    name: Sploiteca
    overlayMap: orangemap2k.jpg
challenges:
  showSolvedNotifications: false
  showHints: false
  showMitigations: false
  codingChallengesEnabled: solved # Options: never  solved  always
  xssBonusPayload: '<iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/771984076&color=%23ff5500&auto_play=true&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe>'
  safetyOverride: false
  showFeedbackButtons: true
hackingInstructor:
  avatarImage: JuicyBot.png
  
products:
  - name: "Wall-E"
    price: 1099
    deluxePrice: 999
    limitPerUser: 5
    description: "This is an emotional support robot. He got you!"
    image: walle.png
    reviews:
      - { text: "He makes me feel loved", author: admin }
      - { text: "Has made me vulnerable :(.", author: bob }
  - name: "Ultron"
    description: "He is your friend. He will kill your enemies"
    price: 1100
    deluxePrice: 990
    image: ultron.png
    reviews:
      - {
          text: "He killed my neighbours. I have never slept so soundly",
          author: fred,
        }
  - name: "Edward Scissorhands"
    description: "Has scissors for hands, and could be trained to be your hair stylist."
    price: 2300
    image: edward.png
    reviews:
      - { text: "My hair has never been more voluminous. 7/7", author: admin }
  - name: "Optimus Prime"
    description: "He's your trainer. He will make sure you get things done.(perhaps violently)"
    price: 2000
    image: optimus.png
  - name: "Rumba"
    description: "Now a self-learning vaccuum, that is your cleaning buddy!"
    price: 2500
    deluxePrice: 2000
    limitPerUser: 5
    image: rumba.png
  - name: "Martha"
    description: "She's your caretaker. She'll ensure your basic survival."
    price: 1600
    image: martha.png
    reviews:
      - {
          text: "I ate three meals for the first time in 6 months. I feel so cared for!",
          author: susan,
        }
  - name: "Kronos"
    description: "Your car is your best friend"
    price: 4000
    limitPerUser: 5
    image: kronos.png
  - name: "Stephen"
    description: "Will help you with your Maths homework!"
    price: 800
    image: stephen.png
  - name: "Hector"
    description: "O-Saft is an easy to use tool to show information about SSL certificate and tests the SSL connection according given list of ciphers and various SSL configurations."
    price: 1430
    image: hector.png
    urlForProductTamperingChallenge: "https://shorturl.at/nwEVZ"
  - name: "Santa"
    description: "You don't need people to give you gifts. Santa's coming to town!"
    price: 5390
    image: santa.png
    useForChristmasSpecialChallenge: true
  - name: "Snippy"
    description: "Donot have time to get a hair cut? Well you have a personal barber"
    price: 2988
    image: snippy.png
    keywordsForPastebinDataLeakChallenge:
      - "12345"
      - "23456"
  - name: "Benjamin"
    description: "Will help with english.(He is quite a grammar nazi)"
    price: 999
    image: benjamin.png
    deletedDate: "2017-04-28"
  - name: "Alex"
    description: "Will read to you."
    price: 3200
    image: alex.png
  - name: "Harper"
    description: 'Massive decoration opportunities with these OWASP Juice Shop or CTF Extension <a href="https://www.stickeryou.com/products/owasp-juice-shop/794" target="_blank">sticker pages</a>! Each page has 16 stickers on it.'
    price: 2211
    image: harper.png
  - name: "Robbie"
    description: 'Get one of these <a href="https://www.stickeryou.com/products/owasp-juice-shop/794" target="_blank">temporary tattoos</a> to proudly wear the OWASP Juice Shop or CTF Extension logo on your skin! If you tweet a photo of yourself with the tattoo, you get a couple of our stickers for free! Please mention <a href="https://twitter.com/owasp_juiceshop" target="_blank"><code>@owasp_juiceshop</code></a> in your tweet!'
    price: 1540
    image: robbie.png
    reviews:
      - {
          text: "I straight-up gots nuff props fo'these tattoos!",
          author: ronald,
        }
  - name: "Samuel"
    description: "Your personal assisstant. Will handle your daily schedule."
    price: 3600
    image: samuel.png
  - name: "Orlando"
    description: "Organizes your messes."
    price: 6550
    image: orlando.png
  - name: "Jordan"
    description: "Will talk to you if you feel lonely"
    price: 2240
    quantity: 5
    limitPerUser: 5
    image: jordan.png
    reviews:
      - { text: "Jordan helps me de-clutter my thoughts", author: andrew }
      - { text: "Wonderful conversations after a tiring day", uthor: bob }
  - name: "Woody"
    description: "Keeps the fireplace running"
    price: 570
    image: woody.png
  - name: "Jeremy"
    description: "Will help you plan your meals"
    price: 860
    image: jeremy.png
    reviews:
      - { text: "Hit my protein goals this month", author: josh }
  - name: "Quill"
    description: "never lets you run out of pens."
    price: 130
    image: quill.png
  - name: "hedwig"
    description: "Handles your mails"
    price: 500
    limitPerUser: 5
    image: hedwig.png
  - name: "Hydro"
    description: "Will remind you that you are capable but need to drink water."
    price: 900
    image: hydro.png
  - name: "Benedict"
    description: "Will politely tell those who try to contact you that you are occupied."
    price: 90
    image: benedict.png # Exif metadata contains "OpenSCAD" as subtle hint...
    fileForRetrieveBlueprintChallenge: JuiceShop.stl # ...to blueprint file type
    exifForBlueprintChallenge:
      - OpenSCAD
  - name: "R2D2"
    description: "Will shoot at burglers"
    price: 278
    quantity: 0
    image: r2d2.png
    deletedDate: "2020-12-24"
  - name: "Casper"
    description: "Projects ghosts on halloween"
    price: 140
    image: casper.png
    deletedDate: "2017-07-01"
  - name: "Doc"
    description: "Books all your doctor appointments"
    price: 450
    image: doc.png
  - name: "UTOR"
    description: 'your personal plumber'
    price: 670
    image: utor.png
    reviews:
      - { text: "The pipings were fixed in places i didn't know they were broken", author: ivor }
  - name: "Nest"
    description: "Your very own bug-control. No wasps nor flies"
    price: 360
    image: nest.png
    deletedDate: "2017-09-20"
  - name: "Pwning OWASP Juice Shop"
    description: '<em>The official Companion Guide</em> by Bj√∂rn Kimminich available <a href="https://leanpub.com/juice-shop">for free on LeanPub</a> and also <a href="https://pwning.owasp-juice.shop">readable online</a>!'
    price: 5.99
    image: pwning.png
    reviews:
      - {
          text: "Even more interesting than watching Interdimensional Cable!",
          author: morty,
        }
  - name: "Coolio"
    description: "Cool all your drinks in minutes for your insufficiently planned parties"
    price: 2999
    quantity: 3
    limitPerUser: 1
    image: coolio.png
  - name: "Chilly"
    description: "Get your ice in mere seconds"
    price: 3000
    quantity: 0
    image: chilly.png
  - name: "OWASP Snakes and Ladders - Web Applications"
    description: 'This amazing web application security awareness board game is <a href="https://steamcommunity.com/sharedfiles/filedetails/?id=1969196030">available for Tabletop Simulator on Steam Workshop</a> now!'
    price: 0.01
    quantity: 8
    image: owaspSnake.png
    reviews:
      - {
          text: "Wait for a 10$ Steam sale of Tabletop Simulator!",
          author: bjoernOwasp,
        }
  - name: "OWASP Snakes and Ladders - Mobile Apps"
    description: 'This amazing mobile app security awareness board game is <a href="https://steamcommunity.com/sharedfiles/filedetails/?id=1970691216">available for Tabletop Simulator on Steam Workshop</a> now!'
    price: 0.01
    quantity: 0
    image: owaspMobile.png
    reviews:
      - {
          text: "Here yo' learn how tha fuck ta not show yo' goddamn phone on camera!",
          author: rapper,
        }
  - name: "inferno"
    description: "Your personal pest control."
    price: 370
    quantity: 0
    image: inferno.png
    reviews:
      - { text: "Rad, dude!", author: roderick }
      - { text: "I never knew i had this many rats in the house", author: susan }
      - {text: "Happy getting rid of the cheese traps",author: bender,}
  - name: 'Bernie'
    description: "Will help you quit smoking. n-1 smoke a month"
    price: 260
    quantity: 0
    limitPerUser: 1
    image: bernie.png
    reviews:
      - { text: "Kept me from finishing two boxes in a day", author: harper }
      - { text: "I managed to go 3 days without a smoke", author: alex }
  - name: "Juice Shop Adversary Trading Card (Common)"
    description: 'Common rarity "Juice Shop" card for the <a href="https://docs.google.com/forms/d/e/1FAIpQLSecLEakawSQ56lBe2JOSbFwFYrKDCIN7Yd3iHFdQc5z8ApwdQ/viewform">Adversary Trading Cards</a> CCG.'
    price: 2.99
    deluxePrice: 0.99
    deletedDate: "2020-11-30"
    limitPerUser: 5
    image: juiceTrading.png
    reviews:
      - { text: "Ooooh, puny human playing Mau Mau, now?", author: bender }
  - name: "Juice Shop Adversary Trading Card (Super Rare)"
    description: 'Super rare "Juice Shop" card with holographic foil-coating for the <a href="https://docs.google.com/forms/d/e/1FAIpQLSecLEakawSQ56lBe2JOSbFwFYrKDCIN7Yd3iHFdQc5z8ApwdQ/viewform">Adversary Trading Cards</a> CCG.'
    price: 99.99
    deluxePrice: 69.99
    deletedDate: "2020-11-30"
    quantity: 2
    limitPerUser: 1
    image: juiceCard.png
    reviews:
      - {
          text: "Mau Mau with bling-bling? Humans are so pathetic!",
          author: bender,
        }
  - name: 'Juice Shop "Permafrost" 2020 Edition'
    description: 'Exact version of <a href="https://github.com/juice-shop/juice-shop/releases/tag/v9.3.1-PERMAFROST">OWASP Juice Shop that was archived on 02/02/2020</a> by the GitHub Archive Program and ultimately went into the <a href="https://github.blog/2020-07-16-github-archive-program-the-journey-of-the-worlds-open-source-code-to-the-arctic">Arctic Code Vault</a> on July 8. 2020 where it will be safely stored for at least 1000 years.'
    price: 9999.99
    quantity: 1
    limitPerUser: 1
    image: juiceEdition.png
    reviews:
      - {
          text: "üßä Let it go, let it go üé∂ Can't hold it back anymore üé∂ Let it go, let it go üé∂ Turn away and slam the door ‚ùÑÔ∏è",
          author: rapper,
        }
  - name: "Dingus"
    description: "Will make sure you have sufficient productive hours."
    price: 5000
    quantity: 1
    image: dingus.png
    reviews:
      - {text: "It didn't let me move until i completed my work",author: sam,}
      - {
          text: "I thought i could take easy breaks. Apparently no.",author: stanley,}
  - name: "Suga"
    description: 'Will help you cut out excessive sugar'
    price: 1000
    quantity: 3
    limitPerUser: 1
    image: suga.png
    reviews:
      - {
          text: "I miss my 20g of sugar a day. I do feel better though.",author: martha,}
  - name: "20th Anniversary Celebration Ticket"
    description: 'Get your <a href="https://20thanniversary.owasp.org/" target="_blank">free üé´ for OWASP 20th Anniversary Celebration</a> online conference! Hear from world renowned keynotes and special speakers, network with your peers and interact with our event sponsors. With an anticipated 10k+ attendees from around the world, you will not want to miss this live on-line event!'
    price: 0.00000000000000000001
    deletedDate: "2021-09-25"
    limitPerUser: 1
    image: 20thTicket.png
    reviews:
      - { text: "I'll be there! Will you, too?", author: bjoernOwasp }

memories:
  - image: "magn(et)ificent!-1571814229653.jpg"
    caption: "Magn(et)ificent!"
    user: bjoernGoogle
  - image: "my-rare-collectors-item!-[Ã≤ÃÖ$Ã≤ÃÖ(Ã≤ÃÖ-Õ°¬∞-Õú ñ-Õ°¬∞Ã≤ÃÖ)Ã≤ÃÖ$Ã≤ÃÖ]-1572603645543.jpg"
    caption: "My rare collectors item! [Ã≤ÃÖ$Ã≤ÃÖ(Ã≤ÃÖ Õ°¬∞ Õú ñ Õ°¬∞Ã≤ÃÖ)Ã≤ÃÖ$Ã≤ÃÖ]"
    user: bjoernGoogle
  - image: "favorite-hiking-place.png"
    caption: "I love going hiking here..."
    geoStalkingMetaSecurityQuestion: 14
    geoStalkingMetaSecurityAnswer: "Daniel Boone National Forest"
  - image: "IMG_4253.jpg"
    caption: "My old workplace..."
    geoStalkingVisualSecurityQuestion: 10
    geoStalkingVisualSecurityAnswer: "ITsec"
ctf:
  showFlagsInNotifications: false
  showCountryDetailsInNotifications: none # Options: none  name  flag  both
  countryMapping: ~
